version: '3.8'

services:
  web:
    build: .
    command: ["/app/run.sh"]
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

volumes:
  postgres_data: